### ISSUE TITLE
Ship the new syntax

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1445]
- [x] #837
- [ ] #978, #1373 (same fix apparently)
- [x] #1376
- [x] #1422
- [x] #1434
- [x] #1435
- [x] #1442
- [x] #1443
- [x] #1444
- [x] #1446
- [x] #1447
- [x] #1453
- [x] #1454
- [x] #1457
- [x] #1472
- [x] #1501
- [x] #1506
- [ ] #1507
- [x] #1508
- [x] #1510
- [x] #1533

Stretch goal:
- [x] #1494 <- edit: seems like we do have a unifying solution. Fred is working on it.
- [ ] #1514 JSX gives newcomers some of the most confusing errors

**Comment by let-def** [comment]
Working in #1422.

**Comment by chenglou** [comment]
That was an amazingly smooth release! I've forwarded the remaining stuff to #1577.

Thanks everyone!
