### ISSUE TITLE
List of parsing issues from accidentally using a reserved keyword

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1494]
Some of these might be false alarms

- [ ] #1475: `sig`
- [ ] #1400: doesn't allow overloading of list syntax
- [x] #1361: dangerous keyword swapping
- [ ] #1257: `end`/`begin`
- [ ] #1208, #1093: swapped `match`/`switch`
- [ ] #1108: `obj`
- [ ] #1095: `to`
- [ ] #1047: `then`
- [x] #824: request for simply allowing keywords to be arguments \* 
- [x] #714: request for simply allowing keywords to be record fields names \*

\* Probably the best options, if possible

**Comment by bsansouci** [comment]
also `obj##val`, someone mentioned it in #main discord.

**Comment by chenglou** [comment]
Seems like we have a unifying solution to kill all of these at once. Stay tuned in around a week.

**Comment by chenglou** [comment]
Example messages we should have:

```
let x = module 5

Syntax error inside the `let` expression. The word `module` is a reserved keyword. Please choose another name.
```

**Comment by chenglou** [comment]
All fixed through #1541. Amazing.
