### ISSUE TITLE
Ship 3.0.1

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1577]
Last time we did an issue list, things went amazingly well. I think I'll start organizing it every release so that we know what to work on.

- [ ] #978, #1373 (same fix apparently)
- [ ] #1507, #1554 (same one?)
- [ ] #1514 JSX gives newcomers some of the most confusing errors. Highest pri, but really hard. Requires a refactor I think.
- [ ] #1549 <- this would be great
- [ ] #1562
- [x] #1580
- [x] #1616
- [x] #1635
- [ ] #1648

Bonus:

- [x] #1500

**Comment by chenglou** [comment]
Shipped
