### ISSUE TITLE
Spacing cleanup:

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#54]
Here's three somewhat related tasks that make a nice unit of work. None of them are particularly difficult:
- [ ] Separate module items according to convention: https://github.com/facebook/Reason/issues/41
- [x] Trim whitespace in printer: https://github.com/facebook/Reason/issues/53
- [ ] Reindent comments correctly when formatting: https://github.com/facebook/Reason/issues/44

**Comment by chenglou** [comment]
Gonna bump this a bit. At least a space between different item types "e.g. types vs let" inside modules would be nice.

**Comment by IwanKaramazow** [comment]
I'm working on this.

**Comment by jordwalke** [comment]
Cool, I've wanted this for a long time!

**Comment by IwanKaramazow** [comment]
I've got some questions:

- Should variants & extensible variants be seen as the same group?
```
module NottyString = {
  type props = {
    attr,
    text: string,
    style: LayoutSupport.LayoutTypes.cssStyle,
    children: list element
  };

  type tag 'props +=
    | StringTag :tag props;

  let createElement ::attr=A.empty ::style=LayoutSupport.defaultStyle ::text children =>
    NativeElement StringTag {attr, text, style, children};
};
```

- Should we group `modules`, `module types` and/or `classes`?
Example:
```
module NottyString = {
  type props = {
    attr,
    text: string,
    style: LayoutSupport.LayoutTypes.cssStyle,
    children: list element
  };

  type tag 'props +=
    | StringTag :tag props;

  let createElement ::attr=A.empty ::style=LayoutSupport.defaultStyle ::text children =>
    NativeElement StringTag {attr, text, style, children};
};
module Div = {
  type props = {style: LayoutSupport.LayoutTypes.cssStyle, children: list element};

  type tag 'props +=
    | VoidTag :tag props;

  let createElement ::style=LayoutSupport.defaultStyle children =>
    NativeElement VoidTag {style, children};
};
```
There's no spacing between module definition `NottyString` & module definition `Div`.

**Comment by hcarty** [comment]
A newline between type definitions and between modules helps a lot with readability. The one exception I can think of is recursively defined types (`type a and type b`).

**Comment by yawaramin** [comment]
FWIW, I put a blank line after any item that takes more than one line--type definitions, modules, bindings, etc.

**Comment by jaredly** [comment]
fixed!
